# Header
menu:

  主页: /
  数字游民: /digital_nomad
  环球旅居: /travel
  自我提升: /self-improvement
  英文工具化: / english_learning
  宝石买手: /gemstones
  知识星球: /knowledge_planet
  # home: /
  # digital: /digital
  # travel: /travel
  # gembuy: /gembuy
  # knowledge_planet: /knowledge_planet
  #Tags: /tags

rss: /atom.xml 

# User Info
user_name: 不上班公社
user_avatar: http://q7fm0u7rl.bkt.clouddn.com/WechatIMG19.png
user_location: Earth
user_description: "数字游民｜旅居世界：旅行，工作，生活。成长。"
user_contact: yeyework@gmail.com
user_introduction: 
github_username: hillsgit
twitter_username: ehazon
weibo_username:
zhihu_username: 不上班公社yeye
facebook_username:
linkedin_username:

# Content
excerpt_link: Read More
fancybox: true

# display widgets at the bottom of index pages (pagination == 2)
#index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# 评论系统
# 不要用别人的 uid, 自己去注册一个吧
use_livere: true
livere_uid: MTAyMC8yOTE4Ni81NzUz

use_disqus: false
disqus_url: https://haojen.disqus.com/embed.js

# Miscellaneous
google_analytics:
favicon: http://q7fm0u7rl.bkt.clouddn.com/WechatIMG18.png
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:

# Highlight code
# do ensure u have closed all the highlight choices in ur root _config.yml
# currently we provided 6 choices based on highlight script
# highlight_default, highlight_light, highlight_github, highlight_rainbow, highlight_vs, highlight_atom
block_highlight: highlight_rainbow
